# https://taskfile.dev

version: "3"

tasks:
  build:
    desc: Build the Docker using buildx
    cmds:
      - docker buildx build --platform linux/arm64 -t caravan/caravan-lab:latest .

  builddc:
    desc: Build the Docker image for Docker Compose
    cmds:
      - docker compose build

  up:
    desc: Run the Docker container
    cmds:
      - docker compose up -d

  down:
    desc: Stop the Docker container
    cmds:
      - docker compose down

  shell_a:
    desc: Open a shell in the Docker container A
    cmds:
      - docker compose exec node_a bash

  iex_a:
    desc: Open an iex shell in the Docker container A
    cmds:
      - docker compose exec node_a ./bin/caravan_lab remote

  shell_b:
    desc: Open a shell in the Docker container B
    cmds:
      - docker compose exec node_b ./bin/caravan_lab remote

  iex_b:
    desc: Open an iex shell in the Docker container B
    cmds:
      - docker compose exec node_b ./bin/caravan_lab remote

  shell_c:
    desc: Open a shell in the Docker container C
    cmds:
      - docker compose exec node_c ./bin/caravan_lab remote

  iex_c:
    desc: Open an iex shell in the Docker container C
    cmds:
      - docker compose exec node_c ./bin/caravan_lab remote
